name: release-arm64-darwin

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: ./build.sh

      - name: Release artifact
        uses: softprops/action-gh-release@v1
        with:
          files: |
            debian_bullseye_arm64_sysroot.tar.xz
